// Generated by CoffeeScript 1.10.0
(function() {
  var App;

  App = (function() {
    function App() {}

    App.prototype.run = function() {};

    return App;

  })();

  window.app = new App();

  app.run();

}).call(this);
